export {default as HomePage} from "./HomePage/Home";
export {default as AboutPage} from "./AboutPage/About"
export {default as RegistrationPage} from "./RegistrationPage/Registration";
export {default as ContactPage} from "./ContactPage/Contact";
export {default as FileComplaintsPage} from "./FileComplaintsPage/File";
export {default as RatingsPage} from "./RatingsPage/Ratings";
export {default as EligibilityPage} from "./EligibilityPage/Eligibility";
export {default as ApplicationsPage} from "./ApplicationsPage/Applications";
export {default as AccreditationPage} from "./AccreditationPage/Accreditation";
export {default as LogComplaintsPage} from "./LogComplaintPage/LogComplaint";
export {default as BusinessRegistrationPage} from "./BusinessRegistrationPage/BusinessRegistration"
export {default as DashboardPage} from "./DashboardPage/DashboardPage";
export {default as DetailsPage} from "./DetailsPage/DetailsPage";
export {default as AnalyticsPage} from "./AnalyticsPage/AnalyticsPage";
export {default as ReportsPage} from "./ReportsPage/ReportsPage";
export {default as SettingsPage} from "./SettingsPage/SettingsPage";
export {default as HelpPage} from "./HelpPage/HelpPage";
export {default as Forgot} from "./RegistrationPage/Forgot";
export {default as ProfilePage} from "./ProfilePage/ProfilePage";
 
